version: '3.8'

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2_proxy
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAMS=http://nginx:80
      - OAUTH2_PROXY_REDIRECT_URL=https://<app_url>/oauth2/callback
      - OAUTH2_PROXY_CLIENT_ID=<client_id>
      - OAUTH2_PROXY_CLIENT_SECRET=<client_secret>
      - OAUTH2_PROXY_COOKIE_SECRET=<cookie_secret>
      - OAUTH2_PROXY_PROVIDER=google
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      #- OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true #uncomment this to bypass the oauth default page
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - oauth2-proxy
    restart: unless-stopped
