version: '3.8'

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2_proxy
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_PROVIDER=azure
      - OAUTH2_PROXY_CLIENT_ID=<client_id>
      - OAUTH2_PROXY_CLIENT_SECRET=<client_secret>
      - OAUTH2_PROXY_AZURE_TENANT=<tenant_id>
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/<tenant_id>/v2.0
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAMS=http://nginx:80
      - OAUTH2_PROXY_REDIRECT_URL=https://<app_url>/oauth2/callback
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_COOKIE_SECRET=<cookie_secret>
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_LOGGING_DEBUG=true
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - oauth2-proxy
    restart: unless-stopped

# Important information
# When using the Azure Auth provider with nginx and the cookie session store you may find the cookie is too large and doesn't get passed through correctly.
# Increasing the proxy_buffer_size in nginx should resolve this.
# Just add these lines inside http block in the end.
# File location is /etc/nginx/nginx.conf  (Base nginx which is installed on vm)
#proxy_buffer_size   128k;
#proxy_buffers   4 256k;
#proxy_busy_buffers_size   256k;
